name: neubrutalism_ui
description: A Flutter package that provides a set of Neubrutalism-style UI components that you can use to build beautiful and functional user interfaces for your apps. The package includes components such as buttons, cards, forms, and icons, all with a unique, modern design that's inspired by the Neubrutalism design philosophy.
maintainer: Deepraj Baidya <@deepraj02>
repository: https://github.com/deepraj02/neubrutalism_ui.git
issue_tracker: https://github.com/deepraj02/neubrutalism_ui/issues/
version: 0.1.2

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
